services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/Playwright
    environment:
      - DISPLAY=host.docker.internal:0  # Łączy się z Twoim serwerem X11 na Windowsie
    command: pytest tests/ --headed
    tty: true